Add Meta Changes
tailcallhq/tailcallhq.github.io pull request #269
Opened 2024-06-02 15:00 UTC by Bhavyajain21

/claim #268 
/fixes #268

2024-06-02 15:16 UTC, tusharmath commented
<img width="299" alt="Screenshot 2024-06-02 at 8 46 08 PM" src="https://github.com/tailcallhq/tailcallhq.github.io/assets/194482/0b90e52c-4f4b-40df-ac3a-cc92119596b9">

Use an appropriate `sidebar_label` for overflowing text

2024-06-02 15:27 UTC, Bhavyajain21 commented
Changes made @tusharmath

2024-06-02 15:35 UTC, Bhavyajain21 commented
I've updated my PR. Please review @tusharmath

2024-06-02 17:38 UTC, Bhavyajain21 commented
I have added the sidebar_label property

2024-06-02 19:30 UTC, tusharmath requested changes

2024-06-02 19:30 UTC, tusharmath commented on docs/N+1.md
> +slug: tailcall-introspection-solving-n-plus-one
```suggestion
slug: graphql-n-plus-one-problem-solved-tailcall
```

2024-06-02 19:30 UTC, tusharmath commented on docs/N+1.md
> +sidebar_label: N+1 Issue Solution
```suggestion
sidebar_label: N+1 Issue
```

2024-06-02 19:30 UTC, tusharmath commented on docs/apollo-studio.md
> +slug: integrate-tailcall-apollo-studio-graphql-optimization
```suggestion
slug: integrate-apollo-studio-graphql-tailcall
```

2024-06-02 19:30 UTC, tusharmath commented on docs/auth.md
> +slug: granular-access-control-graphql-authentication
```suggestion
slug: field-level-access-control-graphql-authentication
```

2024-06-02 19:30 UTC, tusharmath commented on docs/auth.md
> +sidebar_label: Granular Access Control
```suggestion
sidebar_label: Authentication
```

2024-06-02 19:30 UTC, tusharmath commented on docs/auth.md
> +title: Granular Access Control with GraphQL Authentication
```suggestion
title: Field Level GraphQL Authentication
```

2024-06-02 19:30 UTC, tusharmath commented on docs/cli.md
> +title: Master GraphQL with TailCall CLI
```suggestion
title: Command Line Reference
```

2024-06-02 19:30 UTC, tusharmath commented on docs/cli.md
> +slug: tailcall-cli-graphql-configuration-tool
```suggestion
slug: tailcall-graphql-cli
```

2024-06-02 19:30 UTC, tusharmath commented on docs/cli.md
> +sidebar_label: TailCall CLI
```suggestion
sidebar_label: Command Line Reference
```

2024-06-02 19:30 UTC, tusharmath commented on docs/client-tuning.md
> +title: Optimizing Client Performance
```suggestion
title: Optimizing GraphQL Client Performance
```

2024-06-02 19:30 UTC, tusharmath commented on docs/client-tuning.md
> +slug: client-performance-tuning
```suggestion
slug: graphql-client-performance-tuning
```

2024-06-02 19:30 UTC, tusharmath commented on docs/configuration.mdx
> +title: Tailcall Config Conversion
```suggestion
title: Tailcall Configuration Formats
```

2024-06-02 19:30 UTC, tusharmath commented on docs/configuration.mdx
> +sidebar_label: Config Format Conversion
```suggestion
sidebar_label: Config Format
```

2024-06-02 19:30 UTC, tusharmath commented on docs/configuration.mdx
> +slug: tailcall-cli-configuration-format-conversion
```suggestion
slug: tailcall-graphql-configuration-format-conversion
```

2024-06-02 19:30 UTC, tusharmath commented on docs/context.md
> +title: Tailcall Context Mechanism
```suggestion
title: GraphQL Resolver Context
```

2024-06-02 19:30 UTC, tusharmath commented on docs/context.md
> +slug: tailcall-dynamic-context-mechanism
```suggestion
slug: graphql-resolver-context-tailcall
```

2024-06-02 19:30 UTC, tusharmath commented on docs/context.md
> +sidebar_label: Dynamic Context Mechanism
```suggestion
sidebar_label: Resolver Context
```

2024-06-02 19:30 UTC, tusharmath commented on docs/conventions.md
> +title: Tailcall Refines GraphQL
```suggestion
title: GraphQL Best Practices
```

2024-06-02 19:30 UTC, tusharmath commented on docs/conventions.md
> +slug: graphql-naming-conventions-tailcall
```suggestion
slug: graphql-best-practices-tailcall
```

2024-06-02 19:30 UTC, tusharmath commented on docs/conventions.md
> +sidebar_label: GraphQL Naming Conventions
```suggestion
sidebar_label: Best Practices
```

2024-06-02 19:30 UTC, tusharmath commented on docs/data-dog.md
>  title: Data Dog
```suggestion
title: Data Dog Telemetry Integration
```

2024-06-02 19:30 UTC, tusharmath commented on docs/data-dog.md
> +sidebar_label: Telemetry Data Analysis
```suggestion
slug: graphql-data-dog-telemetry-tailcall
sidebar_label: Data Dog Integration
```

2024-06-02 19:30 UTC, tusharmath commented on docs/environment-variables.md
> +title: Managing Environment Variables
```suggestion
title: Reading Environment Variables
```

2024-06-02 19:30 UTC, tusharmath commented on docs/environment-variables.md
> +slug: environment-variables-guide
```suggestion
slug: graphql-environment-variables
```

2024-06-02 19:30 UTC, tusharmath commented on docs/execution-strategy.md
> +slug: data-access-optimization
```suggestion
slug: graphql-data-access-parallel-vs-sequence
```

2024-06-02 19:30 UTC, tusharmath commented on docs/execution-strategy.md
> +sidebar_label: Data Access Optimization
```suggestion
sidebar_label: Sequence vs Parallel
```

2024-06-02 19:30 UTC, tusharmath commented on docs/getting-started.mdx
> +slug: /guides/getting-started-with-graphql-using-tailcall
```suggestion
slug: /getting-started-with-graphql
```

2024-06-02 19:30 UTC, tusharmath commented on docs/grpc.md
> +slug: /guides/graphql-on-grpc
```suggestion
slug: graphql-grpc-tailcall
```

2024-06-02 19:30 UTC, tusharmath commented on docs/honey-comb.md
> +sidebar_position: 4
```suggestion
```

2024-06-02 19:30 UTC, tusharmath commented on docs/honey-comb.md
> +slug: telemetry-honeycomb-guide
```suggestion
slug: graphql-honeycomb-telemetry-tailcall
```

2024-06-02 19:30 UTC, tusharmath commented on docs/http-cache.md
> +slug: http-cache-guide
```suggestion
slug: graphql-http-cache-guide-tailcall
```

2024-06-02 19:30 UTC, tusharmath commented on docs/http2.md
> +slug: http2-guide
```suggestion
slug: graphql-http2-guide-tailcall
```

2024-06-02 19:30 UTC, tusharmath commented on docs/logging.md
> +sidebar_label: Logging Levels
```suggestion
title: Logging Levels Configuration
description: Learn how to configure log levels in Tailcall to obtain insights into code execution and address software development challenges. Discover the available log levels, set verbosity via environment variables, and understand the hierarchy of log levels for effective logging.
slug: graphql-logging-levels-tailcall
sidebar_label: Logging Levels
```

2024-06-02 19:30 UTC, tusharmath commented on docs/new-relic.md
> +title: Telemetry with New Relic
```suggestion
title: New Relic Telemetry Integration
```

2024-06-02 19:30 UTC, tusharmath commented on docs/new-relic.md
> +slug: telemetry-newrelic-guide
```suggestion
slug: graphql-newrelic-guide-telemetry
```

2024-06-02 19:30 UTC, tusharmath commented on docs/scripting.md
> +slug: http-scripting-guide
```suggestion
slug: graphql-javascript-customization
```

2024-06-02 19:30 UTC, tusharmath commented on docs/scripting.md
> +title: Scripting with Tailcall
```suggestion
title: Javascript Extension
```

2024-06-02 19:30 UTC, tusharmath commented on docs/tailcall-on-aws.md
> +slug: tailcall-aws-deployment
```suggestion
slug: graphql-aws-deployment-tailcall
```

2024-06-02 19:30 UTC, tusharmath commented on docs/telemetry.md
> +slug: /telemetry-guide
```suggestion
slug: graphql-telemetry-guide
```

2024-06-02 19:30 UTC, tusharmath commented on docs/telemetry.md
> +title: Telemetry in Tailcall
```suggestion
title: GraphQL Telemetry
```

2024-06-02 19:30 UTC, tusharmath commented on docs/watch-mode.md
>  title: Watch Mode
```suggestion
title: Tailcall Server Watch Mode
```

2024-06-02 19:30 UTC, tusharmath commented on docs/watch-mode.md
> +slug: watch-mode-guide
```suggestion
slug: graphql-watch-mode-tailcall
```

2024-06-03 03:23 UTC, Bhavyajain21 commented
@tusharmath thanks for the suggestions. I've updated the PR.

2024-06-03 05:35 UTC, tusharmath commented
Please run the build locally once before pushing. The CI is failling.

2024-06-03 05:37 UTC, tusharmath requested changes
There are 29 files in this folder where we expected changes, however only 24 were changed.

2024-06-03 05:40 UTC, Bhavyajain21 commented
Sure @tusharmath , will check and update

2024-06-03 07:03 UTC, Bhavyajain21 commented
@tusharmath have updated all the files in the folder, and the build should also be good now!

2024-06-03 09:48 UTC, tusharmath approved these changes

2024-06-03 09:48 UTC, merged