Implementing authentication in graphql
tailcallhq/tailcallhq.github.io pull request #404
Opened 2024-07-30 04:04 UTC by shegz101

Here is an outline for the topic" implementing authentication in graphql." I systematically created an outline that will aid the writer in quickly writing a good article on this topic. The outline contains all the major concepts and practical implementation of GraphQl authentication.

2024-08-02 03:50 UTC, shegz101 commented
@Frenzyritz13 Amit said I should reach out to you and that you are the one in charge of reviewing PRs from now on. Thank you!

2024-08-11 21:22 UTC, shegz101 commented
@tusharmath please you can try re-merging it now. All checks have passed. Thank you! Just so you know, this is the second PR to create an outline for the topic above, which is one of the topics @amitksingh1490 gave to me.

2024-08-11 21:27 UTC, shegz101 commented
> @tusharmath please you can try re-merging it now. All checks have passed. Thank you! Just so you know, this is the second PR to create an outline for the topic above, which is one of the topics @amitksingh1490 gave to me.

I think @Frenzyritz13 is in charge of reviewing it. Thank you!

2024-08-13 06:14 UTC, amitksingh1490 requested changes

2024-08-13 06:14 UTC, amitksingh1490 commented on outlines/implementing-authentication-in-graphql.md
> +D. Server-Side Implementation (Apollo Server and JWT)
```suggestion
D. Server-Side Implementation (Tailcall Server and JWT)
```

2024-08-13 06:14 UTC, amitksingh1490 commented on outlines/implementing-authentication-in-graphql.md
> +```grapql
```suggestion
```graphql
```

2024-08-13 06:14 UTC, amitksingh1490 commented on outlines/implementing-authentication-in-graphql.md
> +```grapql
```suggestion
```graphql
```

2024-08-13 06:14 UTC, amitksingh1490 commented on outlines/implementing-authentication-in-graphql.md
> +B. GraphQL Official Documentation
```suggestion

B. GraphQL Official Documentation
```

2024-08-13 06:14 UTC, amitksingh1490 commented on outlines/implementing-authentication-in-graphql.md
> +- Tools used for tracing, logging, and performance monitoring
use tailcall

2024-08-13 06:15 UTC, amitksingh1490 commented
Added comments, moving it to draft

2024-08-14 04:42 UTC, shegz101 commented
@amitksingh1490 I have implemented the changes.

2024-08-14 04:42 UTC, shegz101 commented
> Added comments, moving it to draft

Thank you. I have committed the changes.

2024-08-14 06:14 UTC, amitksingh1490 commented
This PR has unnecessary file changes. Please keep the changes limited to the scope of work of this PR

2024-08-14 06:40 UTC, shegz101 commented
> This PR has unnecessary file changes. Please keep the changes limited to the scope of work of this PR

Yes, I am having some issues with that. Seems files from other branches are being merged. I will delete/close this PR, then create a new one and tag you.

2024-08-14 07:14 UTC, shegz101 commented
> This PR has unnecessary file changes. Please keep the changes limited to the scope of work of this PR

@amitksingh1490 I have removed the unnecessary file changes. Thank you!

2024-08-14 10:37 UTC, amitksingh1490 commented on outlines/implementing-authentication-in-graphql.md
> +B. Implementing Authorization Logic
```suggestion
B. Using Tailcall Authentication directive
```

2024-08-14 10:40 UTC, closed without merging